#!/usr/bin/env ruby
require 'getoptlong'
require 'pp'
require 'yaml'

def parse_cmd_line
  opts = GetoptLong.new(
    [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
    [ '--file', '-f', GetoptLong::REQUIRED_ARGUMENT ],
    [ '--offset', '-o', GetoptLong::REQUIRED_ARGUMENT ],
    [ '--test', '-t', GetoptLong::NO_ARGUMENT ],
  )

  opt = {}
  opts.each {|k, v| opt[k.gsub(/^-*/, '').to_sym] = v } rescue exit 1
  unless opt[:file]
    $stderr.puts "No logfile to read. Use -f [LOGFILE]."
    exit 1
  end
  opt[:offset] ||= "#{opt[:file]}.offset"

  if opt[:help]
    puts <<-EOF
  logtail2 [OPTION]...
  Tails a log file keeping track of what lines have been processed.

    -f, --file=FILE    read lines from FILE, may contain * or ? wildcards.
    -o, --offset=FILE  keep offset information in FILE.
    -t, --test         test mode, do not update offset file.
    --help, -h      show this help

  If offset file is not specified, defaults to using the log file
  with the .offset extension added.

  Exit status is 0 if OK, non-zero otherwise.

  Report bugs to <jesus@mindjolt.com>.
    EOF
    exit 0
  end
  opt
end

class Offset
  attr_accessor :filename, :offset

  def initialize filename, offset
    @filename = filename
    @offset = offset
  end

  def self.read file
    YAML::load(File.read(file))
  end

  def to_s
    "Offset(#{filename}:#{offset})"
  end
end

class Logtail
  attr_accessor :file, :state_file, :test

  def run
    puts "Starting at offset #{offset}"
    filenames.dup.drop_while {|fn| fn != offset.filename }.each do |fn|
      puts "Processing file #{fn}"
    end
  end

private
  def filenames
    @filenames ||= Dir[file].sort
  end

  def offset
    @offset ||= begin
      Offset.read(state_file)
    rescue
      Offset.new(filenames.first, 0)
    end
  end
end

opt = parse_cmd_line
l = Logtail.new
l.file = opt[:file]
l.state_file = opt[:offset]
l.test = !opt[:test].nil?
l.run
